name: neonpen
description: A Flutter package to add a Neon Pen style on text.
version: 2.0.5
homepage: https://github.com/turlvo/neonpen

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
